[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
escrow_prc = "3EXJ5DHYdqNungWGWR2S9wNMMucCr2pRVjPitfLFDfTi"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
